### ISSUE TITLE
SGT Frog Dropdown doesn't work in other pages

### ISSUE THREAD

**Issue by christhofer** [bberenz/sgtfrog#4]
Sgt Frog dropdown at the navbar doesn't expand anything. It expands only in https://www.steamgifts.com/%C4%85ccount/settings/ribbit

I have turned off all userstyle & scripts, but it still doesn't expand.
I'm using Chrome. Haven't tried Firefox.

**Comment by akberenz** [comment]
Fixed via 071b16b8dbf7cb05cb4d0982310c0f56c2f6237e.
Be sure to check for updates in your script manager to get this applied.

**Comment by christhofer** [comment]
Yup it's fixed
Thank you very much
