### ISSUE TITLE
Find similar button inside giveaway pages looks weird when the giveaway ended.

### ISSUE THREAD

**Issue by christhofer** [bberenz/sgtfrog#5]
The button then shares the same line with the ads, because there is no more join button.
![screenshot](http://i.imgur.com/x97uJ9i.png)

**Comment by akberenz** [comment]
Oops, I usually run around with adblock, so I forget everywhere I need to test with it off.
Fixed via 49ab7d3098e08cbabeb2ce8e2f4a468223dd4053, the search button will take up the entire width now on closed giveaways.

**Comment by christhofer** [comment]
yes, it is fixed for ended giveaways, but the button now doesn't appear on running giveaway
![screenshot](http://i.imgur.com/xkdk1Wr.png)

**Comment by akberenz** [comment]
Looks like a problem with a certain setting combination, so I need to come up with a better testing plan before the next feature.
Should be addressed correctly now, sorry for the trouble.
